# 6CS012 - Worksheet 0: Solutions
## A Tutorial and Assessment on Python and NumPy for Deep Learning
---

## 4.1 Exercise on Functions

### Task - 1: Unit Converter

In [3]:
def convert_length(value, direction):
    """
    Converts length between meters and feet.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'm_to_ft' or 'ft_to_m'.

    Returns:
        float: The converted length value.
    """
    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value / 3.28084


def convert_weight(value, direction):
    """
    Converts weight between kilograms and pounds.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'kg_to_lbs' or 'lbs_to_kg'.

    Returns:
        float: The converted weight value.
    """
    if direction == 'kg_to_lbs':
        return value * 2.20462
    elif direction == 'lbs_to_kg':
        return value / 2.20462


def convert_volume(value, direction):
    """
    Converts volume between liters and gallons.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'l_to_gal' or 'gal_to_l'.

    Returns:
        float: The converted volume value.
    """
    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value / 0.264172


def unit_converter():
    """
    Main function that prompts user to choose a conversion type
    (length, weight, or volume), input a value, and displays the result.
    Handles invalid input using try-except.

    Returns:
        float: The converted result, or None for invalid input.
    """
    print("Choose conversion type:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (liters <-> gallons)")

    try:
        choice = input("Enter 1, 2, or 3: ").strip()

        if choice == '1':
            direction = input("Enter direction (m_to_ft / ft_to_m): ").strip()
            value = float(input("Enter value: "))
            result = convert_length(value, direction)
            print(f"Result: {result:.4f}")

        elif choice == '2':
            direction = input("Enter direction (kg_to_lbs / lbs_to_kg): ").strip()
            value = float(input("Enter value: "))
            result = convert_weight(value, direction)
            print(f"Result: {result:.4f}")

        elif choice == '3':
            direction = input("Enter direction (l_to_gal / gal_to_l): ").strip()
            value = float(input("Enter value: "))
            result = convert_volume(value, direction)
            print(f"Result: {result:.4f}")

        else:
            print("Invalid choice. Please enter 1, 2, or 3.")
            return None

        return result

    except ValueError:
        print("Invalid input. Please enter a numeric value.")
        return None


# Call the function
unit_converter()

Choose conversion type:
1. Length (meters <-> feet)
2. Weight (kg <-> lbs)
3. Volume (liters <-> gallons)
Result: 32.4932


32.493156

### Task - 2: Mathematical Operations on a List

In [4]:
def compute_sum(numbers):
    """
    Computes the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of all elements.
    """
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    """
    Computes the average of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of all elements.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot compute average of an empty list.")
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The maximum element.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of an empty list.")
    max_val = numbers[0]
    for n in numbers:
        if n > max_val:
            max_val = n
    return max_val


def compute_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The minimum element.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of an empty list.")
    min_val = numbers[0]
    for n in numbers:
        if n < min_val:
            min_val = n
    return min_val


def math_operations():
    """
    Prompts user to choose a mathematical operation and input a list of numbers,
    then performs and displays the result. Handles invalid input with try-except.

    Returns:
        float: The result of the selected operation, or None on error.
    """
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = input("Enter 1, 2, 3, or 4: ").strip()
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.strip().split()]

        if len(numbers) == 0:
            raise ValueError("The list is empty.")

        if choice == '1':
            result = compute_sum(numbers)
            print(f"Sum: {result}")
        elif choice == '2':
            result = compute_average(numbers)
            print(f"Average: {result}")
        elif choice == '3':
            result = compute_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == '4':
            result = compute_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid choice.")
            return None

        return result

    except ValueError as e:
        print(f"Error: {e}")
        return None


# Call the function
math_operations()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Maximum: 9.0


9.0

---
## 4.2 Exercise on List Manipulation

In [5]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    """Returns every other element starting from index 0."""
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))  # Expected: [1, 3, 5]

[1, 3, 5]


In [6]:
# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """Returns a sublist from start to end (inclusive)."""
    return lst[start:end + 1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # Expected: [3, 4, 5]

[3, 4, 5]


In [7]:
# 3. Reverse a List Using Slicing
def reverse_list(lst):
    """Returns a reversed version of the list using slicing."""
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))  # Expected: [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


In [8]:
# 4. Remove the First and Last Elements
def remove_first_last(lst):
    """Returns the list without the first and last elements."""
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))  # Expected: [2, 3, 4]

[2, 3, 4]


In [9]:
# 5. Get the First n Elements
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))  # Expected: [1, 2, 3]

[1, 2, 3]


In [10]:
# 6. Extract Elements from the End
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))  # Expected: [4, 5]

[4, 5]


In [11]:
# 7. Extract Elements in Reverse Order (every second, from second-to-last)
def reverse_skip(lst):
    """Returns every second element starting from the second-to-last, moving backward."""
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))  # Expected: [5, 3, 1]

[5, 3, 1]


---
## 4.3 Exercise on Nested List

In [12]:
# 1. Flatten a Nested List
def flatten(lst):
    """Flattens a one-level nested list into a single list."""
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

print(flatten([[1, 2], [3, 4], [5]]))  # Expected: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [13]:
# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    """Returns the element at the given list of indices in a nested list."""
    element = lst
    for idx in indices:
        element = element[idx]
    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(lst, [1, 2]))  # Expected: 6

6


In [14]:
# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """Recursively computes the sum of all elements in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Expected: 21

21


In [15]:
# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """Removes all occurrences of elem from a nested list."""
    return [item for item in
            [[x for x in sublist if x != elem] for sublist in lst]]

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # Expected: [[1], [3], [4, 5]]

[[1], [3], [4, 5]]


In [16]:
# 5. Find the Maximum Element in a Nested List
def find_max(lst):
    """Recursively finds the maximum element in a nested list."""
    max_val = None
    for item in lst:
        if isinstance(item, list):
            candidate = find_max(item)
        else:
            candidate = item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val

print(find_max([[1, 2], [3, [4, 5]], 6]))  # Expected: 6

6


In [17]:
# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """Counts how many times elem appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # Expected: 3

3


In [18]:
# 7. Flatten a List of Lists of Lists (Deep Flatten)
def deep_flatten(lst):
    """Recursively flattens a deeply nested list into a single list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # Expected: [1,2,3,4,5,6,7,8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [19]:
# 8. Nested List Average
def average_nested(lst):
    """Computes the average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1, 2], [3, 4], [5, 6]]))  # Expected: 3.5

3.5


---
## 10.1 Basic Vector and Matrix Operations with NumPy

### Problem - 1: Array Creation

In [22]:
import numpy as np

# 1. Empty array of size 2x2
empty_arr = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_arr)

# 2. All-ones array of size 4x2
ones_arr = np.ones((4, 2))
print("\n2. All-ones 4x2 array:\n", ones_arr)

# 3. Array filled with a specific fill value (e.g., 7), shape 3x3
full_arr = np.full((3, 3), 7)
print("\n3. Array filled with 7 (3x3):\n", full_arr)

# 4. Zeros array with same shape as an existing array
existing = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(existing)
print("\n4. Zeros like existing array:\n", zeros_like_arr)

# 5. Ones array with same shape as an existing array
ones_like_arr = np.ones_like(existing)
print("\n5. Ones like existing array:\n", ones_like_arr)

# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. NumPy array from list:", np_array)

1. Empty 2x2 array:
 [[2.16851034e+243 4.27242994e+180]
 [3.65588327e+233 2.20892684e+161]]

2. All-ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like existing array:
 [[0 0 0]
 [0 0 0]]

5. Ones like existing array:
 [[1 1 1]
 [1 1 1]]

6. NumPy array from list: [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

In [23]:
import numpy as np

# 1. Array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array 10 to 49:\n", arr_range)

# 2. 3x3 matrix with values 0 to 8
matrix_0_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0 to 8):\n", matrix_0_8)

# 3. 3x3 identity matrix
identity = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity)

# 4. Random array of size 30 and its mean
rand_arr = np.random.random(30)
print("\n4. Mean of random array of size 30:", rand_arr.mean())

# 5. 10x10 random array - min and max
rand_10x10 = np.random.random((10, 10))
print("\n5. Min:", rand_10x10.min(), "| Max:", rand_10x10.max())

# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((6, 6))
border_arr[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:\n", checkerboard)

1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array of size 30: 0.5528001751661368

5. Min: 0.003932662970489997 | Max: 0.9999941040876272

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. 2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations

In [24]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add
print("1. x + y:\n", x + y)

# 2. Subtract
print("\n2. x - y:\n", x - y)

# 3. Multiply with integer
print("\n3. x * 3:\n", x * 3)

# 4. Square of each element
print("\n4. x squared:\n", np.square(x))

# 5. Dot products
print("\n5a. Dot product v . w:", np.dot(v, w))
print("5b. Dot product x . v:\n", np.dot(x, v))
print("5c. Dot product x . y:\n", np.dot(x, y))

# 6. Concatenate x and y along rows (axis=0), v and w along column
concat_rows = np.concatenate((x, y), axis=0)
print("\n6a. x and y concatenated along rows:\n", concat_rows)
concat_col = np.concatenate((v, w))  # v and w are 1D
print("6b. v and w concatenated:", concat_col)

# 7. Concatenate x and v - will raise error
print("\n7. Attempting to concatenate x and v:")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"Error: {e}")
    print("Reason: x has shape", x.shape, "and v has shape", v.shape,
          "- mismatched dimensions cannot be concatenated directly.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5a. Dot product v . w: 219
5b. Dot product x . v:
 [29 77]
5c. Dot product x . y:
 [[19 22]
 [50 58]]

6a. x and y concatenated along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. v and w concatenated: [ 9 10 11 12]

7. Attempting to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x has shape (2, 2) and v has shape (2,) - mismatched dimensions cannot be concatenated directly.


### Problem - 4: Matrix Operations

In [25]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
product_A_Ainv = np.dot(A, A_inv)
print("1. A * A_inv (should be Identity):\n", np.round(product_A_Ainv, decimals=10))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.allclose(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("(AB)^T == B^T * A^T?", np.allclose(AB_T, BT_AT))

1. A * A_inv (should be Identity):
 [[1. 0.]
 [0. 1.]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T? True


In [26]:
import numpy as np

# Solve system of equations:
# 2x - 3y + z  = -1
# x  - y  + 2z = -3
# 3x + y  - z  =  9

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])

B_sys = np.array([-1, -3, 9])

# Method 1: Inverse Method (X = A_inv * B)
A_sys_inv = np.linalg.inv(A_sys)
X_inverse = np.dot(A_sys_inv, B_sys)
print("Solution using Inverse Method:")
print(f"x = {X_inverse[0]:.4f}, y = {X_inverse[1]:.4f}, z = {X_inverse[2]:.4f}")

# Method 2: np.linalg.solve
X_solve = np.linalg.solve(A_sys, B_sys)
print("\nSolution using np.linalg.solve:")
print(f"x = {X_solve[0]:.4f}, y = {X_solve[1]:.4f}, z = {X_solve[2]:.4f}")

Solution using Inverse Method:
x = 2.0000, y = 1.0000, z = -2.0000

Solution using np.linalg.solve:
x = 2.0000, y = 1.0000, z = -2.0000


---
## 10.2 Experiment: How Fast is NumPy?

In [27]:
import numpy as np
import time

SIZE = 1_000_000

list_a = list(range(SIZE))
list_b = list(range(SIZE))
np_a = np.array(list_a)
np_b = np.array(list_b)

# 1. Element-wise Addition
start = time.time()
result_list = [list_a[i] + list_b[i] for i in range(SIZE)]
print(f"1. Addition - Python List:  {time.time() - start:.5f} seconds")

start = time.time()
result_np = np_a + np_b
print(f"   Addition - NumPy Array:  {time.time() - start:.5f} seconds")

1. Addition - Python List:  0.10967 seconds
   Addition - NumPy Array:  0.00401 seconds


In [28]:
# 2. Element-wise Multiplication
start = time.time()
result_list = [list_a[i] * list_b[i] for i in range(SIZE)]
print(f"2. Multiplication - Python List:  {time.time() - start:.5f} seconds")

start = time.time()
result_np = np_a * np_b
print(f"   Multiplication - NumPy Array:  {time.time() - start:.5f} seconds")

2. Multiplication - Python List:  0.11418 seconds
   Multiplication - NumPy Array:  0.00296 seconds


In [29]:
# 3. Dot Product
start = time.time()
dot_list = sum(list_a[i] * list_b[i] for i in range(SIZE))
print(f"3. Dot Product - Python List:  {time.time() - start:.5f} seconds")

start = time.time()
dot_np = np.dot(np_a, np_b)
print(f"   Dot Product - NumPy Array:  {time.time() - start:.5f} seconds")

3. Dot Product - Python List:  0.17590 seconds
   Dot Product - NumPy Array:  0.00302 seconds


In [30]:
# 4. Matrix Multiplication (1000x1000)
MAT_SIZE = 1000
mat_list_a = [[float(i * MAT_SIZE + j) for j in range(MAT_SIZE)] for i in range(MAT_SIZE)]
mat_list_b = [[float(i * MAT_SIZE + j) for j in range(MAT_SIZE)] for i in range(MAT_SIZE)]

start = time.time()
result_mat = [[sum(mat_list_a[i][k] * mat_list_b[k][j]
               for k in range(MAT_SIZE))
               for j in range(MAT_SIZE)]
               for i in range(10)]  # Only 10 rows to avoid very long wait
list_time = time.time() - start
print(f"4. Matrix Multiply (10 rows) - Python List:  {list_time:.5f} seconds")

mat_np_a = np.random.rand(MAT_SIZE, MAT_SIZE)
mat_np_b = np.random.rand(MAT_SIZE, MAT_SIZE)

start = time.time()
result_np_mat = np.dot(mat_np_a, mat_np_b)
np_time = time.time() - start
print(f"   Matrix Multiply (1000x1000) - NumPy Array:  {np_time:.5f} seconds")
print(f"   NumPy is vastly faster for full matrix multiplication!")

4. Matrix Multiply (10 rows) - Python List:  1.63862 seconds
   Matrix Multiply (1000x1000) - NumPy Array:  0.03652 seconds
   NumPy is vastly faster for full matrix multiplication!
